[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_privacy_pool = "9uePoqdgaXpqFLQM2ED1GGQrwSEiqe3r6tW1AfsnrrbS"

[programs.devnet]
agent_privacy_pool = "9uePoqdgaXpqFLQM2ED1GGQrwSEiqe3r6tW1AfsnrrbS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx node_modules/.bin/mocha --exit -t 1000000 tests/**/*.ts"
demo-test = "SNAP_DEMO=1 npx tsx node_modules/.bin/mocha --exit -t 1000000 tests/pool.test.ts"

[programs.mainnet]
agent_privacy_pool = "9uePoqdgaXpqFLQM2ED1GGQrwSEiqe3r6tW1AfsnrrbS"
